### ISSUE TITLE
2 examples, neither work, getting "browse directory" view instead

### ISSUE THREAD

**Issue by jcollum** [looker-open-source/extension-examples#54]
kitchensink and helloworld-ts examples. 

![Uploading 2021-06-18_15-03-31.png…]()

Also had to install webpack-dev-server, `yarn develop` failed without it:  

`yarn add -D webpack-dev-server`

Then ran:

```
✗ node --version
v12.21.0

✗ yarn develop
yarn run v1.22.10
$ webpack serve --hot --port 8080 --disable-host-check --config webpack.develop.js
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from http://localhost:8080/
...
webpack 5.10.0 compiled successfully in 17501 ms
ℹ ｢wdm｣: Compiled successfully.
```

Result is screenshot up above. Node 12.

**Comment by bryans99** [comment]
Not sure why you had to add the webpack dev server but its included in package.json and has been since May 6th.

Suspect that you are accessing the development server from the browser directly. The extension framework uses the Looker application URL parameter to load the javascript. The development server does not server up any HTML.
